version: "3"
services:
    web:
        build: ./srcs/myblog/
        links:
            - db
        ports:
            - "5000:5000"
        volumes: 
            - ./srcs/myblog/:/home/myblog/
        environment: 
            FLASK_ENV: development
        depends_on:
            - db
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tinder_clone
        volumes:
            - ./db:/docker-entrypoint-initdb.d/:ro
        